### ISSUE TITLE
Launch Craft Grower Survey

### ISSUE THREAD

**Issue by saseehav** [precision-sustainable-ag/Craft-Management#35]
## Issues ##

- [x] Convert form from Esri to Kobo #3 
- [x] Ingest Cycle 5 contracts  (in spreadsheet) #5  ; #16 
- [x] Convert subplots to expunitID 
- [x] Compile a list of usernames and their associated emails
- [x]  Associate usernames with assigned contracts
- [x]  Make a test contract number #33 
- [x]  Update username and access tables with admin accounts for kobo #34
- [x] Help Tina make all the Grower Accounts (pending)... https://github.com/precision-sustainable-ag/Craft-Management/issues/52 
- [x] Share form will all new usernames for craft - check proper settings
- [x] Move Grower survey into a clean, new kobo form #30 
- [x] Form dupe flow and email confirmation #23  
- [x] Import all the corrected csvs including test contracts and admin accounts
- [x] update the webhook
- [x] test new form and webhook
- [x] V1 Launch for Cycle 5 growers by Oct 20
- [x] Clean cylce 1-4 data to match cycle 5 data for subplot information = exp unit id in our new format
- [ ] Create map displays for confirmation #27 
- [x]  V2 Launch for all growers by Nov 1

**Comment by saseehav** [comment]
map display not created. form ready after testing 11/22 with webhooks and correct accounts
